github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/coomer-downloader",
  "https://serp.co/products/coomer-downloader/reviews/",
  "https://extensions.serp.co/coomer-downloader",
  "https://browserextensions.io/coomer-downloader"
]
